### PR TITLE
Rename template `move` folder to `contract`

### PR DESCRIPTION
**Pull request by 0xmaayan**
Based on user feedbacks, we noticed `move` doesnt mean a lot to new/early Aptos developers and they expect the folder name to be `contract` as it is a more meaningful name and a convention in the web3 developer community and tools

### CODE REVIEW

**Review by 0xaptosj — APPROVED** [review]

**Comment by 0xaptosj** [comment]
can you rename it to `contract` instead of `contracts`? if we want to support multi contract, we need a new layer like `contracts/contract_name/Move.toml`

**Comment by 0xaptosj** [comment]
> > can you rename it to `contract` instead of `contracts`? if we want to support multiple contracts, we need a new layer like `contracts/contract_name/Move.toml`
> 
> could you elaborate? I'd assume `contracts` is a meaningful name to a folder that holds multiple contracts?

currently all templates only have 1 contract, structure is like this
```
| move
|-- Move.toml
|-- sources
```
if you want each template can have multiple contracts, it should look like this
```
| contracts
|-- contract1
|---- Move.toml
|---- sources
|-- contract2
|---- Move.toml
|---- sources
```

If you want to keep each template only have 1 contract, it should look like this
```
| contract
|-- Move.toml
|-- sources
```

**Comment by 0xmaayan** [comment]
> > > can you rename it to `contract` instead of `contracts`? if we want to support multiple contracts, we need a new layer like `contracts/contract_name/Move.toml`
> > 
> > 
> > could you elaborate? I'd assume `contracts` is a meaningful name to a folder that holds multiple contracts?
> 
> each Move.toml corresponds to 1 contract, currently all templates only have 1 contract, structure is like this
> 
> ```
> | move
> |-- Move.toml
> |-- sources
> ```
> 
> if you want each template can have multiple contracts, it should look like this
> 
> ```
> | contracts
> |-- contract1
> |---- Move.toml
> |---- sources
> |-- contract2
> |---- Move.toml
> |---- sources
> ```
> 
> If you want to keep each template only have 1 contract, it should look like this
> 
> ```
> | contract
> |-- Move.toml
> |-- sources
> ```

I see what you mean. Multiple contracts format would also need move scripts modifications.

Ok, let's just use `contract` as each of the current templates only use 1 contract. If in the future we will have multiple contracts we would do the changes accordingly.

**Review by 0xaptosj — APPROVED** [review]
approve to unblock

**Pull request merged**
